# ================= Application =================
spring.application.name=springBootDemoApp


# ================= Database (H2 - In Memory) =================
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# ================= JPA / Hibernate =================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ================= H2 Console (Dev Only) =================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


# ================= DevTools =================
spring.devtools.restart.enabled=true


# ================= Logging =================
logging.level.com.example.springBootDemoApp=INFO


# ================= Multipart Upload =================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# ================= Kafka =================
spring.kafka.bootstrap-servers=localhost:9092


# ================= Kafka Consumer =================
spring.kafka.consumer.group-id=alfresco-ingestion-cg
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false


# ================= Kafka Producer =================
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer